### ISSUE TITLE
Missing icons on buttons

### ISSUE THREAD

**Issue by runejuhl** [linuxserver/docker-digikam#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Using the Digikam app some icons are missing from buttons. I'm guessing the may be missing from the theme?

...and thanks for the Docker image and all your hard work! :)

------------------------------

## Expected Behavior

All icons should be shown on buttons.

## Current Behavior

Not all icons are shown; in the image below the icon is missing making it impossible to figure out what the button does without hovering for a tooltip:

![missing-icons](https://user-images.githubusercontent.com/626791/181744432-b58197bc-c9a1-43f1-ae03-31c35ac5b6e8.png)

Another example where the buttons on top are missing icons: 
![missing-icons2](https://user-images.githubusercontent.com/626791/181747553-8d35c31d-961a-4985-96cc-db882c4ba03d.png)

## Steps to Reproduce

1. Run Digikam
2. Observe
3. ...?
4. Profit!

## Environment
**OS:** Ubuntu 22.04
**CPU architecture:** x86_64
**How docker service was installed:** OS repo

## Docker logs

Nothing relevant as far as I can see:

```
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[custom-init] no custom files found exiting...
[ls.io-init] done.
[guac-init] Auto start not set, application start on login
Starting guacamole-lite websocket server
listening on *:3000
[2022-07-29 12:39:07] [Connection 1]  Client connection open
[2022-07-29 12:39:07] [Connection 1]  Opening guacd connection
[2022-07-29 12:39:07] [Connection 1]  guacd connection open
[2022-07-29 12:39:07] [Connection 1]  Selecting connection type: rdp
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 6.select,3.rdp;
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 4.size,4.3118,14.1319?undefined,2.96;
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/13-keygen
cont-init: info: /etc/cont-init.d/13-keygen exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 1
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/55-autostart-config
cont-init: info: /etc/cont-init.d/55-autostart-config exited 0
cont-init: info: running /etc/cont-init.d/56-openboxcopy
cont-init: info: /etc/cont-init.d/56-openboxcopy exited 1
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun autostart (no readiness notification)
services-up: info: copying legacy longrun guacd (no readiness notification)
services-up: info: copying legacy longrun web (no readiness notification)
services-up: info: copying legacy longrun xrdp (no readiness notification)
services-up: info: copying legacy longrun xrdp-sesman (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
guacd[153]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[153]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[153]: INFO:	Creating new client for protocol "rdp"
guacd[153]: INFO:	Connection ID is "$063badc3-6e01-4b45-8db7-590225a161b4"
guacd[176]: INFO:	Security mode: Negotiate (ANY)
guacd[176]: INFO:	Resize method: none
guacd[176]: INFO:	User "@d100f572-2f6f-4211-a4cb-1f96f65aa22b" joined connection "$063badc3-6e01-4b45-8db7-590225a161b4" (1 users now present)
guacd[176]: INFO:	Loading keymap "base"
guacd[176]: INFO:	Loading keymap "en-us-qwerty"
guacd[176]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[176]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[176]: INFO:	Connected to RDPDR 1.12 as client 0x68d079f2
guacd[176]: INFO:	RDPDR user logged on
[2022-07-29 11:29:28] [Connection 1]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
guacd[176]: ERROR:	User is not responding.
guacd[176]: INFO:	User "@d100f572-2f6f-4211-a4cb-1f96f65aa22b" disconnected (0 users remain)
guacd[176]: INFO:	Last user of connection "$063badc3-6e01-4b45-8db7-590225a161b4" disconnected
guacd[176]: INFO:	Internal RDP client disconnected
guacd[153]: INFO:	Connection "$063badc3-6e01-4b45-8db7-590225a161b4" removed.
guacd[153]: INFO:	Creating new client for protocol "rdp"
guacd[153]: INFO:	Connection ID is "$d6d975f9-2391-4387-a9cd-1230f9514b03"
guacd[542]: INFO:	Security mode: Negotiate (ANY)
guacd[542]: INFO:	Resize method: none
guacd[542]: INFO:	User "@2eb2c97a-764a-4d34-b076-d94b09be0844" joined connection "$d6d975f9-2391-4387-a9cd-1230f9514b03" (1 users now present)
guacd[542]: INFO:	Loading keymap "base"
guacd[542]: INFO:	Loading keymap "en-us-qwerty"
guacd[542]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[542]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[542]: INFO:	Connected to RDPDR 1.12 as client 0xcdf7d51d
guacd[542]: INFO:	RDPDR user logged on
[2022-07-29 12:02:11] [Connection 2]  Closing connection with error:  1001
guacd[153]: INFO:	Creating new client for protocol "rdp"
guacd[153]: INFO:	Connection ID is "$d7b7283c-11d4-4ed8-bad2-22aea4dc3a67"
guacd[3473]: INFO:	Security mode: Negotiate (ANY)
guacd[3473]: INFO:	Resize method: none
guacd[3473]: INFO:	User "@0f8ea8d2-27fe-4d19-956c-1a296801b80a" joined connection "$d7b7283c-11d4-4ed8-bad2-22aea4dc3a67" (1 users now present)
guacd[3473]: INFO:	Loading keymap "base"
guacd[3473]: INFO:	Loading keymap "en-us-qwerty"
guacd[542]: INFO:	RDP server closed connection: Manually logged off.
guacd[542]: INFO:	Internal RDP client disconnected
guacd[3473]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[3473]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[3473]: INFO:	Connected to RDPDR 1.12 as client 0x61deda66
guacd[3473]: INFO:	RDPDR user logged on
guacd[542]: ERROR:	User is not responding.
guacd[542]: INFO:	User "@2eb2c97a-764a-4d34-b076-d94b09be0844" disconnected (0 users remain)
guacd[542]: INFO:	Last user of connection "$d6d975f9-2391-4387-a9cd-1230f9514b03" disconnected
guacd[153]: INFO:	Connection "$d6d975f9-2391-4387-a9cd-1230f9514b03" removed.
[2022-07-29 12:11:37] [Connection 3]  Closing connection with error:  Error: WS was inactive for too long
    at ClientConnection.checkActivity (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:154:24)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
guacd[3473]: ERROR:	User is not responding.
guacd[3473]: INFO:	User "@0f8ea8d2-27fe-4d19-956c-1a296801b80a" disconnected (0 users remain)
guacd[3473]: INFO:	Last user of connection "$d7b7283c-11d4-4ed8-bad2-22aea4dc3a67" disconnected
guacd[3473]: INFO:	Internal RDP client disconnected
guacd[153]: INFO:	Connection "$d7b7283c-11d4-4ed8-bad2-22aea4dc3a67" removed.
guacd[153]: INFO:	Creating new client for protocol "rdp"
guacd[153]: INFO:	Connection ID is "$c7e60697-22b0-4cd7-be05-90875e5aea1a"
guacd[4702]: INFO:	Security mode: Negotiate (ANY)
guacd[4702]: INFO:	Resize method: none
guacd[4702]: INFO:	User "@40747249-cb72-4360-899d-f988e7be0869" joined connection "$c7e60697-22b0-4cd7-be05-90875e5aea1a" (1 users now present)
guacd[4702]: INFO:	Loading keymap "base"
guacd[4702]: INFO:	Loading keymap "en-us-qwerty"
guacd[4702]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[4702]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[4702]: INFO:	Connected to RDPDR 1.12 as client 0x19de3fd6
guacd[4702]: INFO:	RDPDR user logged on
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/13-keygen
cont-init: info: /etc/cont-init.d/13-keygen exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 1
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/55-autostart-config
cont-init: info: /etc/cont-init.d/55-autostart-config exited 0
cont-init: info: running /etc/cont-init.d/56-openboxcopy
cont-init: info: /etc/cont-init.d/56-openboxcopy exited 1
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun autostart (no readiness notification)
services-up: info: copying legacy longrun guacd (no readiness notification)
services-up: info: copying legacy longrun web (no readiness notification)
services-up: info: copying legacy longrun xrdp (no readiness notification)
services-up: info: copying legacy longrun xrdp-sesman (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
guacd[154]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[154]: INFO:	Listening on host 0.0.0.0, port 4822
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
/gclient/node_modules/ws/lib/WebSocketServer.js:127
  if (this.path && this._server._webSocketPaths) {
                                ^

TypeError: Cannot read properties of undefined (reading '_webSocketPaths')
    at WebSocketServer.close (/gclient/node_modules/ws/lib/WebSocketServer.js:127:33)
    at Server.close (/gclient/node_modules/guacamole-lite/lib/Server.js:140:30)
    at process.emit (node:events:513:28)

Node.js v18.6.0
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/13-keygen
cont-init: info: /etc/cont-init.d/13-keygen exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 1
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/55-autostart-config
cont-init: info: /etc/cont-init.d/55-autostart-config exited 0
cont-init: info: running /etc/cont-init.d/56-openboxcopy
cont-init: info: /etc/cont-init.d/56-openboxcopy exited 1
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun autostart (no readiness notification)
services-up: info: copying legacy longrun guacd (no readiness notification)
services-up: info: copying legacy longrun web (no readiness notification)
services-up: info: copying legacy longrun xrdp (no readiness notification)
services-up: info: copying legacy longrun xrdp-sesman (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
guacd[153]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[153]: INFO:	Listening on host 0.0.0.0, port 4822
s6-rc: info: service 99-ci-service-check successfully started
s6-rc: info: service 99-ci-service-check: stopping
s6-rc: info: service 99-ci-service-check successfully stopped
s6-rc: info: service legacy-services: stopping
s6-svwait: fatal: supervisor died
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service 00-legacy: stopping
s6-rc: info: service 00-legacy successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
/gclient/node_modules/ws/lib/WebSocketServer.js:127
  if (this.path && this._server._webSocketPaths) {
                                ^

TypeError: Cannot read properties of undefined (reading '_webSocketPaths')
    at WebSocketServer.close (/gclient/node_modules/ws/lib/WebSocketServer.js:127:33)
    at Server.close (/gclient/node_modules/guacamole-lite/lib/Server.js:140:30)
    at process.emit (node:events:513:28)

Node.js v18.6.0
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/13-keygen
cont-init: info: /etc/cont-init.d/13-keygen exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 1
cont-init: info: running /etc/cont-init.d/50-gid-video
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/55-autostart-config
cont-init: info: /etc/cont-init.d/55-autostart-config exited 0
cont-init: info: running /etc/cont-init.d/56-openboxcopy
cont-init: info: /etc/cont-init.d/56-openboxcopy exited 1
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun autostart (no readiness notification)
services-up: info: copying legacy longrun guacd (no readiness notification)
services-up: info: copying legacy longrun web (no readiness notification)
services-up: info: copying legacy longrun xrdp (no readiness notification)
services-up: info: copying legacy longrun xrdp-sesman (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
guacd[152]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[152]: INFO:	Listening on host 0.0.0.0, port 4822
guacd[152]: INFO:	Creating new client for protocol "rdp"
guacd[152]: INFO:	Connection ID is "$b9cf985a-a00e-4e96-8e94-9f2f4687202e"
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 5.video;
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 5.image;
[2022-07-29 12:39:07] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2022-07-29 12:39:07] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.3118,14.1319?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,12.en-us-qwerty,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
sh: line 1: xauth: command not found

X.Org X Server 1.21.1.4
X Protocol Version 11, Revision 0
Current Operating System: Linux 9d0837c53790 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64
Kernel command line: BOOT_IMAGE=/BOOT/ubuntu_g6a9b9@/vmlinuz-5.15.0-41-generic root=ZFS=rpool/ROOT/ubuntu_g6a9b9 ro usbcore.autosuspend=-1 quiet splash vt.handoff=1
 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.12.log", Time: Fri Jul 29 10:39:08 2022
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7f5e70593010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x00860f01 bx 0x03080800 cx 0x7ed8320b dx 0x178bfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
rdpCreateScreenResources:
rdpmousePreInit: drv 0x55c480ab5770 info 0x55c480bfdfd0, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7f5e719fb2c0
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x55c480ac6bc0 info 0x55c480d88bc0, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7f5e719f6920
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 3116 height 1319
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 3116 height 1319 mmWidth 824 mmHeight 349
rdpRRGetInfo:
  screen resized to 3116x1319
  RRScreenSizeSet ok 1
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 9
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x55c480daeb40
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 3116 height 1319 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0x7f5e64605000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 3116 cy 1319
(EE) Failed to open authorization file ".Xauthority": No such file or directory
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpClientConProcessMsgClientInfo:
  got client info bytes 7072
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 3116 height 1319
rdpLoadLayout: keylayout 0x00000409 variant  display 12
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybBell:
rdpkeybBell:
guacd[173]: INFO:	Security mode: Negotiate (ANY)
guacd[173]: INFO:	Resize method: none
guacd[173]: INFO:	User "@35ddb804-702f-49e5-984b-46b0122055ed" joined connection "$b9cf985a-a00e-4e96-8e94-9f2f4687202e" (1 users now present)
guacd[173]: INFO:	Loading keymap "base"
guacd[173]: INFO:	Loading keymap "en-us-qwerty"
guacd[173]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[173]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[173]: INFO:	Connected to RDPDR 1.12 as client 0xc695671b
guacd[173]: INFO:	RDPDR user logged on
```

**Comment by runejuhl** [comment]
Yes, that is indeed due to a missing theme. The following command solves the issue nicely:

```sh
pacman -Sy breeze --assume-installed=kwayland,frameworkintegration,kirigami2
```

Since this image depends on `baseimage-rdesktop-web` other applications might see the same issue. Would you prefer a PR against https://github.com/linuxserver/docker-baseimage-rdesktop-web or against this repo?

**Comment by runejuhl** [comment]
It looks like the baseimage is still missing the `breeze` package, so this issue should be kept open.

**Comment by runejuhl** [comment]
It seems this issue is still present

**Comment by runejuhl** [comment]
Can't imagine that it's no longer present, I'll try to get around to do a PR against base image soon.

**Comment by teranian** [comment]
This issue still exists. I'm missing a heap of interface icons.

I can find the icons by hovering the mouse cursor, but no amount of restarting or changing themes restores the icons.  

![image](https://user-images.githubusercontent.com/12546984/206933740-5bf93eba-b316-483f-b53a-66e659fbbb43.png)
![image](https://user-images.githubusercontent.com/12546984/206933758-84d9e6e3-9823-4812-ad14-bca61ddcba01.png)

**Comment by teranian** [comment]
I've tried switching Themes (tried all of them) but they're all missing the icons. 
They also don't apply after a restart of the docker, instead it loads the default theme again. Probably a separate issue.

![image](https://user-images.githubusercontent.com/12546984/206933831-24c1c248-5aa1-453e-aaff-99c9eec2b58f.png)

**Comment by keyeh** [comment]
This problem is still happening

**Comment by runejuhl** [comment]
Commenting to keep fresh: this isn't stale, it's just hibernating, waiting for https://github.com/linuxserver/docker-baseimage-rdesktop-web/pull/53.

**Comment by teranian** [comment]
Still exists. This auto stale function is kind of annoying.

**Comment by drizuid** [comment]
There is a PR submitted by @runejuhl but they were asked to correct an issue with their PR and haven't yet. Once they do, we can merge.
