### ISSUE TITLE
Digikam gives black/blank screen after update

### ISSUE THREAD

**Issue by mcwieger** [linuxserver/docker-digikam#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After updating to the latest version I get nothing but a blank KasmVNC screen.

### Expected Behavior

A running Digikam application.

### Steps To Reproduce

Update with Portainer to latest version.
Navigate to the web interface

### Environment

```markdown
Synology 1520+
DSM 6.2 with Docker
Updated with Portainer
Digikam build: LABEL build_version=Linuxserver.io version:- 2023-04-12-ls102 Build-date:- 2023-04-12T16:47:44-05:00
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d --name=digikam -e PUID=1026 -e PGID=101 -e TZ=Europe/Amsterdam -p 8023:3000 -v /volume1/docker/digikam/config:/config -v /volume1/docker/digikam/data:/data -v /volume1/photo:/photo --restart unless-stopped lscr.io/linuxserver/digikam:latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    101
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
2023/04/17 15:13:21 [warn] 178#178: could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
Xvnc KasmVNC 1.1.0 - built Apr 14 2023 03:06:57
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
Openbox-Message: Unable to change to home directory "/root": Permission denied
Openbox-Message: 15:13:22.143: Unable to make directory '/root/.cache/openbox': Permission denied
Openbox-Message: Unable to make directory "/root/.cache/openbox/sessions": Permission denied
Obt-Message: Xinerama extension is not present on the server
Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Error: Access denied
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Traceback (most recent call last):
  File "/usr/lib/openbox/openbox-xdg-autostart", line 196, in <module>
    sys.exit(main())
  File "/usr/lib/openbox/openbox-xdg-autostart", line 66, in main
    else: autofile.run(environments)
  File "/usr/lib/openbox/openbox-xdg-autostart", line 163, in run
    os.chdir(here)
PermissionError: [Errno 13] Permission denied: '/root'
W: [pulseaudio] core-util.c: Failed to open configuration file '/root/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
 2023-04-17 15:14:59,133 [INFO] websocket 0: got client connection from 127.0.0.1
 2023-04-17 15:14:59,178 [PRIO] Connections: accepted: @172.17.0.1_1681737299.164757::websocket
```

**Comment by darkmattercoder** [comment]
Could you try to refresh the browser window several times? I experienced the same issue and did some investigation. Some older release images worked, so I suspected an issue with newer releases. However, I then came to the point where the interface suddenly was visible and did not understand why. After closing and re-opening the browser window and hitting refresh three or four times, the digikam interface appeared
